Python版本的坑-1
Python2.6之
公司的机器部署的是RH6,公司开发需要用到paramiko。
在运行的时候报出了以下的错误：
```python
    File "/home/cigdev/release_repo/imedia/bin/campaign_pipline/cli_driver.py", line 1, in <module>
        from etl import run_ods, run_join, run_gentag, waiting_data_success
    File "/home/cigdev/release_repo/imedia/bin/campaign_pipline/etl.py", line 2, in <module>
        from tools import gen_date, add_emr_step, log_shell_status, has_file_on, parse_date
    File "/home/cigdev/release_repo/imedia/bin/campaign_pipline/tools.py", line 8, in <module>
        import paramiko
    File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
        from paramiko.transport import SecurityOptions, Transport
    File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
        class Transport(threading.Thread, ClosingContextManager):
    File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
        _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
    ValueError: zero length field name in format
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
    File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
    File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
        for thr in _active_threads:
    TypeError: 'NoneType' object is not iterable
    Error in sys.exitfunc:
    Traceback (most recent call last):
    File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
    File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
        for thr in _active_threads:
    TypeError: 'NoneType' object is not iterable
```
经过确认是format的语法在Python2.6与Python2.7版本之间的不兼容问题。
Python2.6中运行
```python
    >>> "{}".format(1)
    Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
    ValueError: zero length field name in format
    >>> "{0}".format(1)
    '1'
```
相关的StackOverflow的链接 https://stackoverflow.com/questions/21034954/valueerror-zero-length-field-name-in-format-in-python2-6-6